### ISSUE TITLE
Gitとslack連携

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#133]
デイリー代用の進捗共有として
https://qiita.com/unsoluble_sugar/items/e42ac352400598a24915

**Comment by z23018nk** [comment]
AIIT交流スペースにて、メンバー限定の「チャネル」作成権限がなく、新規ワークスペースを作成し、Git連携は成功したが。。。
STAY TUNE

**Comment by jun-koyama-h** [comment]
いったん、クローズ
