### ISSUE TITLE
検索ページからAPIを呼び出して結果を結果ページに表示

### ISSUE THREAD

**Issue by ms112323** [jun-koyama-h/team_project#134]

**Comment by Ai-TM** [comment]
@ms112323 
1/11　検索キーワードを翻訳してNewsAPIに投げ、結果を英語でコンソールに表示するところまで完成


![Image](https://github.com/jun-koyama-h/team_project/assets/82172440/b73bb07e-c343-44a9-823f-df09511e0e3b)



以下の通りNewsAPIを仮置き
・期間：1週間前~現在
・メディア(domain)：bbc.co.uk
