### ISSUE TITLE
IssueのLinked Pull Requestにプルリクを紐づける方法

### ISSUE THREAD

**Issue by Ai-TM** [jun-koyama-h/team_project#151]

**Comment by jun-koyama-h** [comment]
![image](https://github.com/jun-koyama-h/team_project/assets/146896373/4a1cb50e-6cdb-4975-8694-68e88549c7e1)

**Comment by Ai-TM** [comment]
・1Issue=1Pull Requestで紐づける
・コマンドからIssueを操作できる
アジャイル開発としては、もう少し細かくストーリーポイントを切って開発するのが良いかも
