### ISSUE TITLE
WebPage作成案

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#16]

**Comment by jun-koyama-h** [comment]
まずはプログラミングありかなしかですよね。

**Comment by ms112323** [comment]
あとは、
インフラどうするか（AWS/Herokuなど）と
開発環境どうするか（ローカル/Dockerなど）
などでしょうか。

**Comment by jun-koyama-h** [comment]
Heroku有料になりましたし、悩ましいところですね。去年の動画見たらRuby on RailsでHerokuとかでしたね。

**Comment by jun-koyama-h** [comment]
こちらいったんとじまーす
