### ISSUE TITLE
api/kvから返却された位置情報に地図のピンを立てる

### ISSUE THREAD

**Issue by ms112323** [jun-koyama-h/team_project#180]

**Comment by ms112323** [comment]
https://github.com/jun-koyama-h/team_project/pull/178
https://github.com/jun-koyama-h/team_project/pull/179

でほぼ対応は完了。
ただ、ローカル環境では正常にピンが立つが、Cloudflareではピンの画像が抜けて表示される（CSSを読み込めていない？）

**Comment by jun-koyama-h** [comment]
https://github.com/PaulLeCam/react-leaflet/issues/453
このあたりの話ですかね。

**Comment by ms112323** [comment]
ありがとうございます！
まさにこの話だと思うのですが、ローカルでは正常で、CloudflareだとNGなのでビルドとかデプロイに関連するのかなと思い調べ中です。

**Comment by jun-koyama-h** [comment]
できているのでクローズ
