### ISSUE TITLE
WEBサイトブレインストーミング

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#22]

**Comment by z23018nk** [comment]
目指す：News on Earth
概要：
Sprint0
プレゼン資料
Sprint１
①キーワード（日本語）入力


Sprint2
②裏側でキーワードを各国言語に翻訳
③（事前に登録した）世界中のニュースサイト検索
④（日本語翻訳して）サイト検索結果テキスト表示

フロント　言語：React

バックエンド　言語

Sprint２～４
⑤地図上（ピンを立てて？）で各国ニュースサイト結果を表示

ツール：
Docker
Git
GitHub Action
VSCode

使用：
 Map上にピンをたてて

使うもの：
オープンストリートマップ
https://www.openstreetmap.org/#map=5/35.604/134.385

**Comment by jun-koyama-h** [comment]
もろもろ方向性が決まったのでクローズ。あとはアジャイル的に。
