### ISSUE TITLE
プレゼン資料作成

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#24]

**Comment by jun-koyama-h** [comment]
https://docs.google.com/presentation/d/1kX6iFwR40xp-IzUKEOuA7ANE0BBkQ-r-VOiqSyykLzw/edit#slide=id.g2a778709617_0_100

**Comment by z23018nk** [comment]
ありがとう！
先生の評価ポイントです。テンショントリアージはその成果を知りたそう。みんなに共有していきましょ
- 心理的安全性
[- テンショントリアージ](https://www.projectsprint.org/ja/v2.2/tips/4-5)
