### ISSUE TITLE
Reactの勉強

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#25]

**Comment by z23018nk** [comment]
[【React.js + Leaflet】ReactLeafletで地図を表示しながらLeafletの理解を深める](https://zenn.dev/micronn/articles/776c702089f16e)

**Comment by z23018nk** [comment]
[React.js](https://kinsta.com/jp/blog/javascript-libraries/)
勉強になります…m(__)m

**Comment by Ai-TM** [comment]
会社で買ってもらったUdemyの講座
ここまでする必要ないと思いますが、ご参考まで
https://www.udemy.com/share/106RPe3@Fgcxk3daZshNg3lmrlOccpDpSD8KzS0gs_OfA0FuZZ9iQU3V11zi2DD9JUTNVzFQtg==/

**Comment by jun-koyama-h** [comment]
いったんくろーず
