### ISSUE TITLE
検索結果がない場合の表示

### ISSUE THREAD

**Issue by z23018nk** [jun-koyama-h/team_project#250]

**Comment by z23018nk** [comment]
記事がない場合の検索結果画面に文言を表示したいです。
「該当の記事はありませんでした」等、いかがでしょうか

![Image](https://github.com/jun-koyama-h/team_project/assets/153108806/5e38c12e-97fe-4821-b88d-cebfba599c97)

**Comment by jun-koyama-h** [comment]
実装していただけると嬉しいです

**Comment by jun-koyama-h** [comment]
メッセージ追加したのでクローズ
