### ISSUE TITLE
インフラ考える

### ISSUE THREAD

**Issue by jun-koyama-h** [jun-koyama-h/team_project#30]

**Comment by jun-koyama-h** [comment]
DBはfirestore使おうか・・・・悩みまする・・・

**Comment by jun-koyama-h** [comment]
Cloud Runで、サイドカーとしてnginxコンテナつかってフロントエンドプロキシにする？

**Comment by jun-koyama-h** [comment]
価格シミュレーションはこちら
https://cloud.google.com/products/calculator-legacy/#id=286be5e5-3c8c-4196-90ae-b03ec6ed38d0

**Comment by jun-koyama-h** [comment]
Cloudflare使った場合、CORS対策でこれ使うみたいな
https://www.cloudflare.com/ja-jp/developer-platform/workers/

**Comment by Ai-TM** [comment]
ChatGPTも機能的にはいけそうですが、APIは別料金らしい・・
やはりGoogle翻訳でしょうか。
https://obot-ai.com/column/10545/


![Image](https://github.com/jun-koyama-h/team_project/assets/82172440/fd9d4a68-e540-4fd0-a8ba-574b3158cc20)



![Image](https://github.com/jun-koyama-h/team_project/assets/82172440/3e2ac6dc-d89b-49e4-882d-37bb6b580f3a)

**Comment by jun-koyama-h** [comment]
ちょとまた考え直します。
Cloud Translation API使う方向です。

**Comment by jun-koyama-h** [comment]
Cloudflare Workers AI使うのでクローズ
