### ISSUE TITLE
世界のニュースサイトPICK UP

### ISSUE THREAD

**Issue by jun-koyama-h** [jun-koyama-h/team_project#31]
APIで提供していないサイトをあげる。  
また、スクレイピングしても利用規約、著作権が問題ないサイトのみ。  
スクレイピングはCPUやメモリ負荷が高いため、別途サーバを作る必要があり費用が発生する。  
最終的に時間に余裕ができたら対応する。

**Comment by jun-koyama-h** [comment]
https://pressgazette.co.uk/media-audience-and-business-data/media_metrics/most-popular-websites-news-world-monthly-2/

https://www.similarweb.com/top-websites/news-and-media/

Slackであげてもらったの転記します。

**Comment by jun-koyama-h** [comment]
ニューヨークタイムズ
https://developer.nytimes.com/
ザ・ガーディアン
https://open-platform.theguardian.com/
BBC
https://bbcnewslabs.co.uk/

**Comment by jun-koyama-h** [comment]
アルジャジーラ
https://api-portal.aljazeera.com/signin?returnUrl=%2F

Wiki
https://en.wikipedia.org/wiki/List_of_news_media_APIs

**Comment by Ai-TM** [comment]
NewsAPI
https://newsapi.org/

**Comment by jun-koyama-h** [comment]
ピックアップしたのでクローズ
