### ISSUE TITLE
KVへAPI設定登録

### ISSUE THREAD

**Issue by jun-koyama-h** [jun-koyama-h/team_project#53]

**Comment by z23018nk** [comment]
先生、KVって何でしょうか。

API設定登録ぜひやってみたいので、教えてくださいm(__)m

**Comment by jun-koyama-h** [comment]
@z23018nk KVはKey Valueの略でCloudflareが標準で持っているNoSQLのことです。
https://db-engines.com/en/system/Cloudflare+Workers+KV

**Comment by jun-koyama-h** [comment]
クローズしま
